<?php

namespace ContainerYtaY3PI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiContext2Service extends App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'Tests\Shared\Infrastructure\Behat\ApiContext' shared autowired service.
     *
     * @return \Tests\Shared\Infrastructure\Behat\ApiContext
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Tests\\Shared\\Infrastructure\\Behat\\ApiContext'] = new \Tests\Shared\Infrastructure\Behat\ApiContext(($container->services['behat.mink.default_session'] ?? $container->load('getBehat_Mink_DefaultSessionService')));
    }
}
