<?php

namespace ContainerYtaY3PI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCrearUsuarioParticularCommandHandlerService extends App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'Eurega\ShoppingList\Application\Command\Usuario\CrearUsuarioParticularCommandHandler' shared autowired service.
     *
     * @return \Eurega\ShoppingList\Application\Command\Usuario\CrearUsuarioParticularCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Eurega\\ShoppingList\\Application\\Command\\Usuario\\CrearUsuarioParticularCommandHandler'] = new \Eurega\ShoppingList\Application\Command\Usuario\CrearUsuarioParticularCommandHandler(($container->privates['Eurega\\ShoppingList\\Application\\Service\\Usuario\\UsuarioParticularCreator'] ?? $container->load('getUsuarioParticularCreatorService')));
    }
}
