<?php

namespace ContainerYtaY3PI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchUsuarioParticularByCriteriaQueryHandlerService extends App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'Eurega\ShoppingList\Application\Query\Usuario\SearchUsuarioParticularByCriteriaQueryHandler' shared autowired service.
     *
     * @return \Eurega\ShoppingList\Application\Query\Usuario\SearchUsuarioParticularByCriteriaQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Eurega\\ShoppingList\\Application\\Query\\Usuario\\SearchUsuarioParticularByCriteriaQueryHandler'] = new \Eurega\ShoppingList\Application\Query\Usuario\SearchUsuarioParticularByCriteriaQueryHandler(($container->privates['Eurega\\ShoppingList\\Application\\Service\\Usuario\\UsuarioParticularByCriteriaSearcher'] ?? $container->load('getUsuarioParticularByCriteriaSearcherService')));
    }
}
