<?php

namespace ContainerYtaY3PI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTactician_Commandbus_Default_Middleware_CommandHandlerService extends App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'tactician.commandbus.default.middleware.command_handler' shared service.
     *
     * @return \League\Tactician\Handler\CommandHandlerMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['tactician.commandbus.default.middleware.command_handler'] = new \League\Tactician\Handler\CommandHandlerMiddleware(($container->privates['tactician.handler.command_name_extractor.class_name'] ??= new \League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor()), ($container->privates['tactician.commandbus.default.handler.locator'] ?? $container->load('getTactician_Commandbus_Default_Handler_LocatorService')), ($container->privates['tactician.handler.method_name_inflector.handle'] ??= new \League\Tactician\Handler\MethodNameInflector\HandleInflector()));
    }
}
