<?php

namespace ContainerYtaY3PI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTactician_Commandbus_Default_Handler_ServiceLocatorService extends App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'tactician.commandbus.default.handler.service_locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['tactician.commandbus.default.handler.service_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Eurega\\ShoppingList\\Application\\Query\\Usuario\\SearchUsuarioParticularByCriteriaQueryHandler' => ['privates', 'Eurega\\ShoppingList\\Application\\Query\\Usuario\\SearchUsuarioParticularByCriteriaQueryHandler', 'getSearchUsuarioParticularByCriteriaQueryHandlerService', true],
            'Eurega\\ShoppingList\\Application\\Command\\Usuario\\CrearUsuarioParticularCommandHandler' => ['privates', 'Eurega\\ShoppingList\\Application\\Command\\Usuario\\CrearUsuarioParticularCommandHandler', 'getCrearUsuarioParticularCommandHandlerService', true],
        ], [
            'Eurega\\ShoppingList\\Application\\Query\\Usuario\\SearchUsuarioParticularByCriteriaQueryHandler' => '?',
            'Eurega\\ShoppingList\\Application\\Command\\Usuario\\CrearUsuarioParticularCommandHandler' => '?',
        ]);
    }
}
