<?php

namespace ContainerYtaY3PI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioParticularByCriteriaSearcherService extends App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'Eurega\ShoppingList\Application\Service\Usuario\UsuarioParticularByCriteriaSearcher' shared autowired service.
     *
     * @return \Eurega\ShoppingList\Application\Service\Usuario\UsuarioParticularByCriteriaSearcher
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Eurega\\ShoppingList\\Application\\Service\\Usuario\\UsuarioParticularByCriteriaSearcher'] = new \Eurega\ShoppingList\Application\Service\Usuario\UsuarioParticularByCriteriaSearcher(($container->privates['Tests\\Shared\\Infrastructure\\Repository\\UsuarioParticularReadRepository'] ??= new \Tests\Shared\Infrastructure\Repository\UsuarioParticularReadRepository()));
    }
}
