<?php

namespace ContainerCkA6dzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTactician_Commandbus_DefaultService extends App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'tactician.commandbus.default' shared service.
     *
     * @return \League\Tactician\CommandBus
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['tactician.commandbus.default'] = new \League\Tactician\CommandBus([($container->privates['tactician.commandbus.default.middleware.command_handler'] ?? $container->load('getTactician_Commandbus_Default_Middleware_CommandHandlerService'))]);
    }
}
