<?php

namespace ContainerYtaY3PI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInMemorySymfonyEventBusService extends App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'Eurega\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus' shared autowired service.
     *
     * @return \Eurega\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Eurega\\Shared\\Infrastructure\\Bus\\Event\\InMemory\\InMemorySymfonyEventBus'] = new \Eurega\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus();
    }
}
