<?php

namespace ContainerYtaY3PI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTactician_Handler_CommandNameExtractor_ClassNameService extends App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'tactician.handler.command_name_extractor.class_name' shared service.
     *
     * @return \League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['tactician.handler.command_name_extractor.class_name'] = new \League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor();
    }
}
