<?php

namespace ContainerYtaY3PI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioParticularGetControllerService extends App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'App\ShoppingList\Backend\Controller\Usuario\UsuarioParticularGetController' shared autowired service.
     *
     * @return \App\ShoppingList\Backend\Controller\Usuario\UsuarioParticularGetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Usuario'.\DIRECTORY_SEPARATOR.'UsuarioParticularGetController.php';

        return $container->services['App\\ShoppingList\\Backend\\Controller\\Usuario\\UsuarioParticularGetController'] = new \App\ShoppingList\Backend\Controller\Usuario\UsuarioParticularGetController(($container->privates['Eurega\\Shared\\Infrastructure\\Bus\\Command\\Tactician\\TacticianCommandBusRead'] ?? $container->load('getTacticianCommandBusReadService')));
    }
}
