<?php

namespace ContainerCkA6dzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_PublicAlias_Tactician_Command_DebugService extends App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.tactician.command.debug' shared service.
     *
     * @return \League\Tactician\Bundle\Command\DebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.tactician.command.debug'] = new \League\Tactician\Bundle\Command\DebugCommand(['default' => ['Eurega\\ShoppingList\\Application\\Query\\Usuario\\SearchUsuarioParticularByCriteriaQuery' => 'Eurega\\ShoppingList\\Application\\Query\\Usuario\\SearchUsuarioParticularByCriteriaQueryHandler', 'Eurega\\ShoppingList\\Application\\Command\\Usuario\\CrearUsuarioParticularCommand' => 'Eurega\\ShoppingList\\Application\\Command\\Usuario\\CrearUsuarioParticularCommandHandler']]);
    }
}
