<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYtaY3PI\App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYtaY3PI/App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerYtaY3PI.legacy');

    return;
}

if (!\class_exists(App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerYtaY3PI\App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer::class, App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer::class, false);
}

return new \ContainerYtaY3PI\App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer([
    'container.build_hash' => 'YtaY3PI',
    'container.build_id' => 'c6ca7f1f',
    'container.build_time' => 1726470312,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYtaY3PI');
