<?php

namespace ContainerCkA6dzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiContextService extends App_ShoppingList_Backend_ShoppingListBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'App\ShoppingList\Backend\Test\Behat\ApiContext' shared autowired service.
     *
     * @return \App\ShoppingList\Backend\Test\Behat\ApiContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Test'.\DIRECTORY_SEPARATOR.'Behat'.\DIRECTORY_SEPARATOR.'ApiContext.php';

        return $container->services['App\\ShoppingList\\Backend\\Test\\Behat\\ApiContext'] = new \App\ShoppingList\Backend\Test\Behat\ApiContext(($container->services['behat.mink.default_session'] ?? $container->load('getBehat_Mink_DefaultSessionService')));
    }
}
